import type { AppProps } from "next/app";
import Head from "next/head";

import "@/styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import Header from "../components/header";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import Providers from "@/providers";

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* Global metadata */}
      <Head>
        <title>Eclat Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Providers>
        <Header />
        <Navbar />
        <main style={{ padding: "20px" }}>
          <Component {...pageProps} />
        </main>
        <Footer />
      </Providers>
    </>
  );
}
